version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws sts get-caller-identity  # Check AWS credentials

  build:
    commands:
      - echo Creating S3 bucket...
      - aws s3api create-bucket --bucket 28june-accawsdevops-codebuild --region us-east-1

  post_build:
    commands:
      - echo Build completed!
