version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install

  pre_build:
    commands:
      - echo Verifying AWS CLI installation...
      - aws --version
      - aws sts get-caller-identity

  build:
    commands:
      - echo Creating S3 bucket...
      - aws s3api create-bucket --bucket my-new-bucket-name --region us-east-1

  post_build:
    commands:
      - echo Build completed!
